interface host {
    gen-random-integer: func() -> u32
}


default world chat-plugin {
    import host: self.host

    record chat-instruction {
        msg: string,
        temp: float32,
        context: bool,
        save: bool,
        pastebin: bool
    }

    variant msg-target {
        myself,
        channel(string)
    }

    export get-chat-instruction: func(line: string) -> option<chat-instruction>

    export handle: func(line: string, sender: msg-target)

    // export run: func(name: string) -> string
}